### ISSUE TITLE
nb_utilの置き場所

### ISSUE THREAD

**Issue by daddygongon** [EAGLE12/nb_util#3]
nb_utilをgrad_research/eagle12の下に置いておくと，面倒です．
nb_utilがsubmoduleとして扱われて，こちらでmergeするときに
	modified:   eagle12/nb_util (modified content, untracked content)
とでて，これが消えません．.gitignoreで消えるかと思ったのですが，ダメなようです．

そこで，nb_utilを独立したgitとしてどこか他へおいて管理してください．
週明けには消しますので，横へよけといてください．

**Comment by daddygongon** [comment]
それとapostrophy(')とか空白をfile名に使わないようにしてください．管理がややこしくなります．
空白はunder_barに置き換え，apostrophyは使わない．としています．

**Comment by jane-john-doe** [comment]
かしこまりました。このリポジトリが、nb_utilのリポジトリになるので、grad_reserchの、nb_utilを消去します。

**Comment by jane-john-doe** [comment]
了解しました。
今後気をつけます。
